main: fr.peaceandcube.pacpi.pAcPI
name: pAcPI
version: 1.2.0
author: YanisBft
website: https://github.com/PeaceAndCubeMC/pAcPI
api-version: 1.13

commands:
  removealltags:
    description: Allows you to remove all tags from a player
    permission: pacpi.removealltags
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/removealltags <player> [<except>]"
  chrono:
    description: Allows you to start and end a chrono
    permission: pacpi.chrono
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/chrono (start|end) <player>"

permissions:
  pacpi.removealltags:
    description: Allows you to remove all tags from a player
    default: op
  pacpi.chrono:
    description: Allows you to start and end a chrono
    default: op
